name: py310-gpu-reader
channels:
  - pytorch-nightly
  - conda-forge
  - nvidia
dependencies:
  - python=3.10.14
  - pytorch-cuda=12.4
  - pytorch
  - torchvision
  - torchaudio
  - pip
  - pip:
    - funasr
    - pypinyin
    - loguru
    - pytest
    - ruff
    - yapf
    - isort
    - ipython
    - jedi-language-server
