name: py310-osx-subalch
channels:
  - pytorch-nightly
  - apple
dependencies:
  - python=3.10.14
  - pytorch
  - torchvision
  - torchaudio
  - pip
  - pip:
    - funasr
    - pypinyin
    - pytest
    - ruff
    - yapf
    - isort
    - ipython
    - jedi-language-server
